#
# web开发构建镜像 Dockerfile
# NGINX Dockerfile
# - 

FROM nginx

MAINTAINER xhx <xiao@bingofresh.com>

# sources.list
# git clone git@github.com:IBBD/docker-compose.git
# 如果导致apt-get Install不成功，可以先注释这句
#ADD ext/sources.list   /etc/apt/sources.list

# 解决时区问题
#env TZ "Asia/Shanghai"
#RUN echo "Asia/Shanghai" > /etc/timezone
#RUN dpkg-reconfigure -f noninteractive tzdata


