- hosts: "{{ host }}"
  vars:
    base_path: /data/apps
    org: registry.bingofresh.com
    project: bingofresh/wx-php
    version: "{{ version }}"
  remote_user: root
  tasks:
  - name: Git pull the latest code
    git: repo=git@gitlab.com:{{ org }}/{{ container }}.git
         dest={{ base_path }}/{{ container }}
         accept_hostkey=yes
         force=yes
         version={{ version }}
    when : version == "develop"
  - name: Add app dir if it doesn't yet exist
    file: path={{ item }} owner=nobody group=docker recurse=yes state=directory
    with_items:
    - "{{ base_path }}/{{ container }}/app"
    when : version == "develop"
  - name: Run Docker iamge with product
    docker:
      name: "{{ container }}-pro"  
      image: "{{ container }}"
#      pull: always
      state: reloaded
      ports:
      - "8002:8000"
    when : version == "master"
  - name: Run Docker image with app volumes
    docker:
      name: "{{ container }}-dev"
  #    image: "{{ org }}/{{ container }}"
      image: "{{ org }}/{{ container }}"
      state: reloaded
  #    pull: always
      ports:
      - "8000:8000"
      volumes:
      - "{{ base_path }}/{{ container }}/app:/usr/src/app"
      command: node /usr/src/app/app.js
    when: version == "develop"
